services:

  db_container:
    image: postgres:16
    container_name: db_container

    environment:
      POSTGRES_DB: visitasdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    volumes:
      - postgres_data:/var/lib/postgresql/data

  myapp_container:
    image: myapp-image
    container_name: myapp_container

    environment:
      DB_HOST: db_container
      DB_NAME: visitasdb
      DB_USER: admin
      DB_PASSWORD: admin123

    depends_on:
      - db_container

  mynginx_container:
    image: nginx:latest
    container_name: mynginx_container

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - myapp_container

volumes:
  postgres_data:
